import type { Metadata } from "next";
import { Fira_Code } from "next/font/google";
import "@/styles/globals.css";
import "@/styles/themes.css";
import { GlobalQueryClient } from "@/providers/query-client-provider";


const firaCode = Fira_Code({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Flash.Y",
    description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="pt-BR">
            <body
                className={`${firaCode.className} ${firaCode.className} antialiased dark`}
            >
                <GlobalQueryClient>
                    {children}
                </GlobalQueryClient>
            </body>
        </html>
    );
}
